using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace IDCM.IDB.DAM
{
    public class CTDRecord
    {
        private string strain_number{get;set;}
        private string other_collection_numbers{get;set;}
        private string genus_name{get;set;}
        private string subspecies_name{get;set;}
        private string variety_name{get;set;}
        private string author{get;set;}
        private string organism_type{get;set;}
        private string history_of_deposit{get;set;}
        private string date_of_isolation{get;set;}
        private string isolated_from{get;set;}
        private string geographic_origin{get;set;}
        private string status{get;set;}
        private string type_strain{get;set;}
        private string optimum_temperature_for_growth{get;set;}
        private string maximum_temperature_for_growth{get;set;}
        private string minimum_temperature_for_growth{get;set;}
        private string application{get;set;}
        private string literature{get;set;}
        private string soursurl{get;set;}
        private string heat_resistance{get;set;}
        private string altitude{get;set;}
        private string humidity_for_environment{get;set;}
        private string ethanol_conditions{get;set;}
        private string tolerances_and_sensitivities{get;set;}
        private string conditions_for_fruiting_or_sporulation{get;set;}
        private string ph_for_environment{get;set;}
        private string biotransformations{get;set;}
        private string single_compounds_tested{get;set;}
        private string enzymes_produced{get;set;}
        private string fine_structure_data{get;set;}
        private string osmophily_and_xerophily{get;set;}
        private string oxygen_relationship{get;set;}
        private string light_conditions{get;set;}
        private string deficiencies{get;set;}
        private string date_of_accession{get;set;}
        private string form_of_supply{get;set;}
        private string conditions_of_water_activity{get;set;}
        private string cell_contents{get;set;}
        private string phenotype{get;set;}
        private string deposited_by{get;set;}
        private string minimum_growth_ph{get;set;}
        private string cellshape{get;set;}
        private string maximum_growth_ph{get;set;}
        private string toxicity_to_other_organisms{get;set;}
        private string restriction_for_destribute{get;set;}
        private string maximum_growthtemperature{get;set;}
        private string hybridization_with_other_strains{get;set;}
        private string rehydration_fluid{get;set;}
        private string temperature_of_hybridization{get;set;}
        private string strainid{get;set;}
        private string serovar{get;set;}
        private string latitude{get;set;}
        private string optimum_minimum_maximum_sugar_concentrations{get;set;}
        private string internal_check_of_identity_at_collection{get;set;}
        private string region{get;set;}
        private string herbarium_no{get;set;}
        private string motileby{get;set;}
        private string genotype{get;set;}
        private string teleomorph_name{get;set;}
        private string taxonomyid{get;set;}
        private string carbon_sources_that_have_been_tested_for_growth{get;set;}
        private string record_type{get;set;}
        private string optimum_minimum_maximum_nacl_concentration{get;set;}
        private string country_of_export{get;set;}
        private string minimum_growth_temperatue{get;set;}
        private string plasmid{get;set;}
        private string date_of_collection{get;set;}
        private string special_form_name{get;set;}
        private string decomposition_and_deteriorating_capacities{get;set;}
        private string metabolites_produced{get;set;}
        private string date_of_update{get;set;}
        private string mutants{get;set;}
        private string history{get;set;}
        private string conditions_for_germination{get;set;}
        private string bio_hazard_level{get;set;}
        private string mating_type{get;set;}
        private string motile{get;set;}
        private string name_at_accept{get;set;}
        private string method_by_which_mutation_was_induced{get;set;}
        private string optimal_growth_temperatue{get;set;}
        private string optimal_growth_ph{get;set;}
        private string collection_method{get;set;}
        private string race{get;set;}
        private string remarks_on_restrictions{get;set;}
        private string type_of_dna_or_rna{get;set;}
        private string temperature_relationships_for_growth{get;set;}
        private string animal_quarantine_no{get;set;}
        private string longitude{get;set;}
        private string isolated_by{get;set;}
        private string antagonistic_activities_against_other_organisms{get;set;}
        private string nutritional_requirements_and_growth_factors_required{get;set;}
        private string sexual_reproduction{get;set;}
        private string temperatue_for_environment{get;set;}
        private string killer_properties_of_yeast{get;set;}
        private string plant_quarantine_no{get;set;}
        private string misapplied_name{get;set;}
        private string depth{get;set;}
        private string country{get;set;}
        private string habitat{get;set;}
        private string hybrids{get;set;}
        private string mta{get;set;}
        private string sexual_behaviour{get;set;}
        private string identified_by{get;set;}
        private string sexual_state{get;set;}
        private string method_of_isolation{get;set;}
        private string sporeforming{get;set;}
        private string state{get;set;}
        private string cellsize{get;set;}
        private string gc_content_of_dna{get;set;}
        private string wall_constituents{get;set;}
        private string anamorph_name{get;set;}
        private string conditions_for_growth_in_liquid_media{get;set;}
        private string staining_reactions{get;set;}
        private string number_of_nuclei{get;set;}
        private string collected_by{get;set;}
        private string substrate{get;set;}
        private string symbiosis{get;set;}
        private string date_of_identification{get;set;}
        private string former_name{get;set;}
        private string source_of_isolation{get;set;}
        private string conditions_for_growth_and_maintenance_on_solid_media{get;set;}
        private string nitrogen_sources_that_have_been_tested_for_growth{get;set;}
        private string hybridization_strain_number{get;set;}
        private string pigment_production_and_autofluorescence{get;set;}
        private string allergenicity{get;set;}
        private string percentage{get;set;}
        private string coenzyme_q_system{get;set;}
        private string mycoparasitism{get;set;}
        private string date_of_deposition{get;set;}
        private string salinity_requirements_for_growth{get;set;}
        private string mode_of_preservation_storage{get;set;}
        private string group{get;set;}
        private string strain{get;set;}
        public const string KeyName = "strain_number";
    }
}
